name: the_india_insights
description: Flutter news app for wordpress platform

version: 1.0.0+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.0
  dio: ^4.0.0
  flutter:
    sdk: flutter
  flutter_html: ^2.1.2
  flutter_widget_from_html: ^0.7.0
  get:
  html: ^0.15.0
  http: ^0.13.3
  intl: ^0.17.0
  loading: ^1.0.2
  path_provider: null
  share: ^2.0.4
  shared_preferences: ^2.0.8
  sqflite: ^2.0.0+4
  url_launcher: ^6.0.11
  uuid: null

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/TIINews.png

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/logoo.png
    - assets/no-internet.png
    - assets/play-button.png
    - assets/boxed/fashion.png
    - assets/boxed/health.png
    - assets/boxed/lifestyle.png
    - assets/boxed/music.png
    - assets/boxed/photography.png
    - assets/boxed/recipies.png
    - assets/boxed/sport.png
    - assets/boxed/travel.png
    - assets/boxed/world.png
    - assets/more/favourite.png
    - assets/more/contact.png
    - assets/more/share.png
    - assets/more/notification.png

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Bold.ttf

    - family: Soleil
      fonts:
        - asset: fonts/Soleil/Soleil-Bold.otf
        - asset: fonts/Soleil/Soleil-Regular.otf
