// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBtsw_mrWHK5oH9ob8D3JyxrQY5eeKalNQ',
//     appId: '1:802669133460:web:c0cf6819bb5f2d6e3abe81',
//     messagingSenderId: '802669133460',
//     projectId: 'indiainsigth',
//     authDomain: 'indiainsigth.firebaseapp.com',
//     storageBucket: 'indiainsigth.appspot.com',
//     measurementId: 'G-R72NH1RSEQ',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCPBqLXm71VTg7JoY3lXbhfBz2GFzGmp0E',
//     appId: '1:802669133460:android:b56c6420551726463abe81',
//     messagingSenderId: '802669133460',
//     projectId: 'indiainsigth',
//     storageBucket: 'indiainsigth.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAxjQC5bw9IccPYI_dBCcqsVPHfFHb2EbQ',
//     appId: '1:802669133460:ios:ccd0ee9c0d965d4e3abe81',
//     messagingSenderId: '802669133460',
//     projectId: 'indiainsigth',
//     storageBucket: 'indiainsigth.appspot.com',
//     iosBundleId: 'com.example.flutterWordpressApp',
//   );
// }
